name: 'Cypress Coverage'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  cypress-coverage:
    environment: coverage
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Start API server in the background
        run: |
          cd back-end &&
          npm install &&
          npm run start &&
          sleep 10 &&
          curl http://localhost:5000 -I
      - name: Run Cypress coverage tests
        uses: cypress-io/github-action@v4.2.0
        with:
          start: npm start
          build: npm run build
          working-directory: ./front-end
