name: 'Jest Coverage'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  jest-coverage:
    environment: coverage
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run Jest coverage tests
        uses: ArtiomTr/jest-coverage-report-action@v2.0.9
        with:
          working-directory: ./back-end
