name: 'Jest Coverage Report'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  coverage:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ArtiomTr/jest-coverage-report-action@v2.0.9
        with:
          coverage-file: /back-end/coverage/coverage-final.json
